---
- name: check distribution release
  fail:
    msg: "ubuntu distribution release not supported: {{ ansible_distribution_release }}"
  when: "ansible_distribution_release not in ['trusty', 'xenial', 'bionic']"

- name: add apt key
  become: yes
  apt_key:
    url: "{{ docker_repository_url }}/gpg"
    id: "{{ docker_gpg_key_fingerprint }}"
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repository_url }} {{ ansible_distribution_release }} stable"
    state: present

- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: install package
  become: yes
  apt:
    pkg: "{{ docker_package_name }}"
    state: latest
  notify: docker | service started
